name: my fiest githgub pipeline
on: 
  schedule:
    - cron: '0/4 * * * *'
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello  world
        run: echo "hello world"
      - name: ckeckout background
        uses: actions/checkout@v4
      - name: list
        run: ls -a
      - name: checking my server
        run: echo "my jon runs a shedule"
       
  

