name: hello git demo
on:
  push:
    branches:
      - main
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: its trail
        run: echo "hello ram"
  build_jo1:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: its trail
        run: echo "hello ram"
